from os import environ

environ['PYGAME_HIDE_SUPPORT_PROMPT'] = "hide"
from pygame.cursors import compile, diamond
from pygame.locals import SYSTEM_CURSOR_HAND, SYSTEM_CURSOR_NO, SYSTEM_CURSOR_WAIT, SYSTEM_CURSOR_ARROW


LeftArrow = [
    '                                                                                                                                ',
    '                                                                                                                                ',
    '                                                                                             XXXXXXXXXXXXXXXXXX                 ',
    '                      XX                                                                 XXXXXX XXXXX XXXXXX                    ',
    '                 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                    ',
    '                     XXX                                                                XXXXXXXXXXXXXXXXXXX                     ',
    '                                                                                            XXXXXX XXXXX XXXXXX                 ',
    '                                                                                                                                ',
    ]

LeftArrow = ((128, 8), (17, 4), *compile(LeftArrow))

RightArrow = [
    '                                                                                                                                ',
    '                 XXXXXX XXXXXXXXXXXX                                                                                            ',
    '                     XXXXXX XXXXXXXXXXXX                                                                 XX                     ',
    '                     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                 ',
    '                      XXXXXX XXXXXXXXXXXX                                                                XXX                    ',
    '                  XXXXXXXXXXXXXXXXXXX                                                                                           ',
    '                                                                                                                                ',
    '                                                                                                                                ',
    ]

RightArrow = ((128, 8), (111, 4), *compile(RightArrow))

UpArrow = [
    '                                                                                                                                ',
    '                                                                XX                                                              ',
    '                                                              XXXXX                                                             ',
    '                                                             X  X  XX                                                           ',
    '                                                                X                                                               ',
    '                                                                X                                                               ',
    '                                                                X                                                               ',
    '                                                                X                                                               ',
    '                                                                X                                                               ',
    '                                                                X                                                               ',
    '                                                                X                                                               ',
    '                                                                X                                                               ',
    '                                                                X                                                               ',
    '                                                                X                                                               ',
    '                                                                X                                                               ',
    '                                                                X                                                               ',
    '                                                                X                                                               ',
    '                                                                X                                                               ',
    '                                                                X                                                               ',
    '                                                                X                                                               ',
    '                                                                X                                                               ',
    '                                                                X                                                               ',
    '                                                                X                                                               ',
    '                                                                X                                                               ',
    '                                                                X                                                               ',
    '                                                                X                                                               ',
    '                                                                X                                                               ',
    '                                                                X                                                               ',
    '                                                                XX                                                              ',
    '                                                              XXXXX                                                             ',
    '                                                            XXXXXXXXX                                                           ',
    '                                                           XXXXXXXXXXXX                                                         ',
    '                                                          XXX XXXXXXXXX                                                         ',
    '                                                          XXXXX XXXXX X                                                         ',
    '                                                          XXXXXXXXX XXX                                                         ',
    '                                                          XXXXXXXXXXXXX                                                         ',
    '                                                           XXXX X  XXXX                                                         ',
    '                                                          XXX       XXX                                                         ',
    '                                                          XX          X                                                         ',
    '                                                                                                                                '
    ]

UpArrow = ((128, 40), (64, 0), *compile(UpArrow))

DownArrow = [
    '                                                                                                                                ',
    '                                                          XX        XXX                                                         ',
    '                                                          XXXX     XXX                                                          ',
    '                                                          XXXXXXXXXXXX                                                          ',
    '                                                          XXXXXXXXXXXX                                                          ',
    '                                                          XXXXXXXXXXXX                                                          ',
    '                                                          XXXXXXXXXXXX                                                          ',
    '                                                          XXXXXXXXXXXXX                                                         ',
    '                                                           XXXXXXXXXX                                                           ',
    '                                                             XXXXXXX                                                            ',
    '                                                              XXXX                                                              ',
    '                                                               XX                                                               ',
    '                                                               XX                                                               ',
    '                                                               XX                                                               ',
    '                                                               XX                                                               ',
    '                                                               XX                                                               ',
    '                                                               XX                                                               ',
    '                                                               XX                                                               ',
    '                                                               XX                                                               ',
    '                                                               XX                                                               ',
    '                                                               XX                                                               ',
    '                                                               XX                                                               ',
    '                                                               XX                                                               ',
    '                                                               XX                                                               ',
    '                                                               XX                                                               ',
    '                                                               XX                                                               ',
    '                                                               XX                                                               ',
    '                                                               XX                                                               ',
    '                                                               XX                                                               ',
    '                                                               XX                                                               ',
    '                                                               XX                                                               ',
    '                                                               XX                                                               ',
    '                                                               XX                                                               ',
    '                                                               XX                                                               ',
    '                                                               XX                                                               ',
    '                                                               XX                                                               ',
    '                                                             XXXXXX                                                             ',
    '                                                              XXXX                                                              ',
    '                                                                                                                                ',
    '                                                                                                                                ',
    ]

DownArrow = ((128, 40), (64, 39), *compile(DownArrow))


SWArrow = [
    '                                                                                                                                ',
    '                                                                                                                                ',
    '                                                                                                                                ',
    '                                                                                                                                ',
    '                                                                                                                                ',
    '                                                                                                                                ',
    '                                                                                             X                                  ',
    '                                                                                          XXX                                   ',
    '                                                                                        XXXXX                                   ',
    '                                                                                      XXXXXX  X                                 ',
    '                                                                                   XXXXX XXXXXXXXXXXX                           ',
    '                                                                                 XXX XX XXXXXXXXX                               ',
    '                                                                                XXXXXXXXXXXXXXXX                                ',
    '                                                                                XXXXXXXXX XXXX                                  ',
    '                                                                               XXXXXXXXXXXX                                     ',
    '                                                                              XXXXX                                             ',
    '                                                                            XX                                                  ',
    '                                                                          X                                                     ',
    '                                                                       XX                                                       ',
    '                                                                     X                                                          ',
    '                                                                  XX                                                            ',
    '                                                                X                                                               ',
    '                                                             XX                                                                 ',
    '                                                          XX                                                                    ',
    '                                                        XX                                                                      ',
    '                                                      X                                                                         ',
    '                                                   XX                                                                           ',
    '                                                XX                                                                              ',
    '                                              XX                                                                                ',
    '                                            X                                                                                   ',
    '                                         XX                                                                                     ',
    '                                       X                                                                                        ',
    '                                XX  XX                                                                                          ',
    '                                XXX                                                                                             ',
    '                               XXXXX                                                                                            ',
    '                                                                                                                                ',
    '                                                                                                                                ',
    '                                                                                                                                ',
    '                                                                                                                                ',
    '                                                                                                                                '
    ]


SWArrow = ((128, 40), (31, 35), *compile(SWArrow))

SEArrow = [
    '                                                                                                                                ',
    '                                                                                                                                ',
    '                                                                                                                                ',
    '                                                                                                                                ',
    '                                                                                                                                ',
    '                                  X                                                                                             ',
    '                                   XXX                                                                                          ',
    '                                   XXXXX                                                                                        ',
    '                                 X  XXX XX                                                                                      ',
    '                           XXXXXXX XXXXXXXXXX                                                                                   ',
    '                              XXXXXXXXXXXXXXXXX                                                                                 ',
    '                                XXXXXXXXXXXXXXXX                                                                                ',
    '                                   XX XXXXXX XXX                                                                                ',
    '                                     XXXXXXXXXXXX                                                                               ',
    '                                          XXXXXXXX                                                                              ',
    '                                                  XX                                                                            ',
    '                                                    XX                                                                          ',
    '                                                       XX                                                                       ',
    '                                                          X                                                                     ',
    '                                                            XX                                                                  ',
    '                                                               X                                                                ',
    '                                                                 XX                                                             ',
    '                                                                   XX                                                           ',
    '                                                                      XX                                                        ',
    '                                                                        XX                                                      ',
    '                                                                           XX                                                   ',
    '                                                                             XX                                                 ',
    '                                                                                XX                                              ',
    '                                                                                  XX                                            ',
    '                                                                                     XX                                         ',
    '                                                                                       XX                                       ',
    '                                                                                          XX   X                                ',
    '                                                                                            XXXXX                               ',
    '                                                                                          XXXXXXXX                              ',
    '                                                                                           XXXXXXXX                             ',
    '                                                                                          XX XX XX                              ',
    '                                                                                                                                ',
    '                                                                                                                                ',
    '                                                                                                                                ',
    '                                                                                                                                '
    ]


SEArrow = ((128, 40), (99, 36), *compile(SEArrow))

NEArrow = [
    '                                                                                                                                ',
    '                                                                                                                                ',
    '                                                                                                                                ',
    '                                                                                                                                ',
    '                                                                                                                                ',
    '                                                                                                                                ',
    '                                                                                                                                ',
    '                                                                                          XXXXXXX                               ',
    '                                                                                            XX XX                               ',
    '                                                                                         XX    X                                ',
    '                                                                                       XX                                       ',
    '                                                                                    XX                                          ',
    '                                                                                  XX                                            ',
    '                                                                               XX                                               ',
    '                                                                             XX                                                 ',
    '                                                                          XX                                                    ',
    '                                                                        XX                                                      ',
    '                                                                     XX                                                         ',
    '                                                                   XX                                                           ',
    '                                                                 X                                                              ',
    '                                                              XX                                                                ',
    '                                                           XX                                                                   ',
    '                                                         XX                                                                     ',
    '                                                      XX                                                                        ',
    '                                                    XX                                                                          ',
    '                                                 XX                                                                             ',
    '                                       XXXXXXXXXXX                                                                              ',
    '                                    XXXXXXX  XXXX                                                                               ',
    '                                  XXXXXXXXXXXXXXX                                                                               ',
    '                               XXXXX XXXXXXX XXX                                                                                ',
    '                             XXXXXXXXXXX XXXXXX                                                                                 ',
    '                          XXXX     X XXXXXXXX                                                                                   ',
    '                            X       XXXXXX                                                                                      ',
    '                                    XXX                                                                                         ',
    '                                   XX                                                                                           ',
    '                                                                                                                                ',
    '                                                                                                                                ',
    '                                                                                                                                ',
    '                                                                                                                                ',
    '                                                                                                                                '
    ]

NEArrow = ((128, 40), (97, 8), *compile(NEArrow))

NWArrow = [
    '                                                                                                                                ',
    '                                                                                                                                ',
    '                                                                                                                                ',
    '                                                                                                                                ',
    '                                                                                                                                ',
    '                                                                                                                                ',
    '                               XXX                                                                                              ',
    '                                XXX  X                                                                                          ',
    '                                 X  XX                                                                                          ',
    '                                      XX                                                                                        ',
    '                                         XX                                                                                     ',
    '                                           XX                                                                                   ',
    '                                              XX                                                                                ',
    '                                                XX                                                                              ',
    '                                                   XX                                                                           ',
    '                                                     XX                                                                         ',
    '                                                        XX                                                                      ',
    '                                                          XX                                                                    ',
    '                                                             XX                                                                 ',
    '                                                               XX                                                               ',
    '                                                                  XX                                                            ',
    '                                                                    XX                                                          ',
    '                                                                       XX                                                       ',
    '                                                                         XX                                                     ',
    '                                                                            XX                                                  ',
    '                                                                              XXX                                               ',
    '                                                                               XXXXXXXXXXXX                                     ',
    '                                                                                XXXXXXXXXXXXX                                   ',
    '                                                                                XXXXXXXXXXXXXXXX                                ',
    '                                                                                 XXX XXXXXXXXXX XX                              ',
    '                                                                                   XXXXX XXXXXXXXXXXX                           ',
    '                                                                                      XXXXXXXXX                                 ',
    '                                                                                        XXXXX                                   ',
    '                                                                                          XXXX                                  ',
    '                                                                                             X X                                ',
    '                                                                                                                                ',
    '                                                                                                                                ',
    '                                                                                                                                ',
    '                                                                                                                                ',
    '                                                                                                                                '
    ]

NWArrow = ((128, 40), (32, 6), *compile(NWArrow))

CursorDict = {
    'N': UpArrow,
    'NE': NEArrow,
    'E': RightArrow,
    'SE': SEArrow,
    'S': DownArrow,
    'SW': SWArrow,
    'W': LeftArrow,
    'NW': NWArrow,
    'Diamond': diamond,
    'Hand': (SYSTEM_CURSOR_HAND,),
    'default': (SYSTEM_CURSOR_ARROW,),
    'IllegalMove': (SYSTEM_CURSOR_NO,),
    'Wait': (SYSTEM_CURSOR_WAIT,)
}
