# noinspection PyUnresolvedReferences
from src import pre_pygame_import


def SetBlockedEvents() -> None:
	import pygame as pg

	pg.event.set_blocked((
		pg.AUDIODEVICEADDED,
		pg.AUDIODEVICEREMOVED,
		pg.FINGERMOTION,
		pg.FINGERUP,
		pg.FINGERDOWN,
		pg.MOUSEWHEEL,
		pg.MULTIGESTURE,
		pg.TEXTINPUT,
		pg.TEXTEDITING,
		pg.WINDOWRESTORED,
		pg.WINDOWCLOSE,
		pg.WINDOWENTER,
		pg.WINDOWEXPOSED,
		pg.WINDOWHIDDEN,
		pg.WINDOWFOCUSGAINED,
		pg.WINDOWHITTEST,
		pg.WINDOWLEAVE,
		pg.WINDOWMOVED,
		pg.WINDOWRESIZED,
		pg.WINDOWSHOWN,
		pg.WINDOWFOCUSLOST,
		pg.WINDOWMAXIMIZED,
		pg.WINDOWMINIMIZED,
		pg.WINDOWSIZECHANGED,
		pg.WINDOWTAKEFOCUS,
		pg.ACTIVEEVENT,
		pg.USEREVENT,
		pg.VIDEOEXPOSE,
	))
