LeftArrow = (
	'                                                                                                                                ',
	'                                                                                                                                ',
	'                                                                                             XXXXXXXXXXXXXXXXXX                 ',
	'                      XX                                                                 XXXXXX XXXXX XXXXXX                    ',
	'                 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                    ',
	'                     XXX                                                                XXXXXXXXXXXXXXXXXXX                     ',
	'                                                                                            XXXXXX XXXXX XXXXXX                 ',
	'                                                                                                                                ',
	)

RightArrow = (
	'                                                                                                                                ',
	'                 XXXXXX XXXXXXXXXXXX                                                                                            ',
	'                     XXXXXX XXXXXXXXXXXX                                                                 XX                     ',
	'                     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                 ',
	'                      XXXXXX XXXXXXXXXXXX                                                                XXX                    ',
	'                  XXXXXXXXXXXXXXXXXXX                                                                                           ',
	'                                                                                                                                ',
	'                                                                                                                                ',
	)

UpArrow = (
	'                                                                                                                                ',
	'                                                                XX                                                              ',
	'                                                              XXXXX                                                             ',
	'                                                             X  X  XX                                                           ',
	'                                                                X                                                               ',
	'                                                                X                                                               ',
	'                                                                X                                                               ',
	'                                                                X                                                               ',
	'                                                                X                                                               ',
	'                                                                X                                                               ',
	'                                                                X                                                               ',
	'                                                                X                                                               ',
	'                                                                X                                                               ',
	'                                                                X                                                               ',
	'                                                                X                                                               ',
	'                                                                X                                                               ',
	'                                                                X                                                               ',
	'                                                                X                                                               ',
	'                                                                X                                                               ',
	'                                                                X                                                               ',
	'                                                                X                                                               ',
	'                                                                X                                                               ',
	'                                                                X                                                               ',
	'                                                                X                                                               ',
	'                                                                X                                                               ',
	'                                                                X                                                               ',
	'                                                                X                                                               ',
	'                                                                X                                                               ',
	'                                                                XX                                                              ',
	'                                                              XXXXX                                                             ',
	'                                                            XXXXXXXXX                                                           ',
	'                                                           XXXXXXXXXXXX                                                         ',
	'                                                          XXX XXXXXXXXX                                                         ',
	'                                                          XXXXX XXXXX X                                                         ',
	'                                                          XXXXXXXXX XXX                                                         ',
	'                                                          XXXXXXXXXXXXX                                                         ',
	'                                                           XXXX X  XXXX                                                         ',
	'                                                          XXX       XXX                                                         ',
	'                                                          XX          X                                                         ',
	'                                                                                                                                '
	)

DownArrow = (
	'                                                                                                                                ',
	'                                                          XX        XXX                                                         ',
	'                                                          XXXX     XXX                                                          ',
	'                                                          XXXXXXXXXXXX                                                          ',
	'                                                          XXXXXXXXXXXX                                                          ',
	'                                                          XXXXXXXXXXXX                                                          ',
	'                                                          XXXXXXXXXXXX                                                          ',
	'                                                          XXXXXXXXXXXXX                                                         ',
	'                                                           XXXXXXXXXX                                                           ',
	'                                                             XXXXXXX                                                            ',
	'                                                              XXXX                                                              ',
	'                                                               XX                                                               ',
	'                                                               XX                                                               ',
	'                                                               XX                                                               ',
	'                                                               XX                                                               ',
	'                                                               XX                                                               ',
	'                                                               XX                                                               ',
	'                                                               XX                                                               ',
	'                                                               XX                                                               ',
	'                                                               XX                                                               ',
	'                                                               XX                                                               ',
	'                                                               XX                                                               ',
	'                                                               XX                                                               ',
	'                                                               XX                                                               ',
	'                                                               XX                                                               ',
	'                                                               XX                                                               ',
	'                                                               XX                                                               ',
	'                                                               XX                                                               ',
	'                                                               XX                                                               ',
	'                                                               XX                                                               ',
	'                                                               XX                                                               ',
	'                                                               XX                                                               ',
	'                                                               XX                                                               ',
	'                                                               XX                                                               ',
	'                                                               XX                                                               ',
	'                                                               XX                                                               ',
	'                                                             XXXXXX                                                             ',
	'                                                              XXXX                                                              ',
	'                                                                                                                                ',
	'                                                                                                                                ',
	)


SWArrow = (
	'                                                                                                                                ',
	'                                                                                                                                ',
	'                                                                                                                                ',
	'                                                                                                                                ',
	'                                                                                                                                ',
	'                                                                                                                                ',
	'                                                                                             X                                  ',
	'                                                                                          XXX                                   ',
	'                                                                                        XXXXX                                   ',
	'                                                                                      XXXXXX  X                                 ',
	'                                                                                   XXXXX XXXXXXXXXXXX                           ',
	'                                                                                 XXX XX XXXXXXXXX                               ',
	'                                                                                XXXXXXXXXXXXXXXX                                ',
	'                                                                                XXXXXXXXX XXXX                                  ',
	'                                                                               XXXXXXXXXXXX                                     ',
	'                                                                              XXXXX                                             ',
	'                                                                            XX                                                  ',
	'                                                                          X                                                     ',
	'                                                                       XX                                                       ',
	'                                                                     X                                                          ',
	'                                                                  XX                                                            ',
	'                                                                X                                                               ',
	'                                                             XX                                                                 ',
	'                                                          XX                                                                    ',
	'                                                        XX                                                                      ',
	'                                                      X                                                                         ',
	'                                                   XX                                                                           ',
	'                                                XX                                                                              ',
	'                                              XX                                                                                ',
	'                                            X                                                                                   ',
	'                                         XX                                                                                     ',
	'                                       X                                                                                        ',
	'                                XX  XX                                                                                          ',
	'                                XXX                                                                                             ',
	'                               XXXXX                                                                                            ',
	'                                                                                                                                ',
	'                                                                                                                                ',
	'                                                                                                                                ',
	'                                                                                                                                ',
	'                                                                                                                                '
	)

SEArrow = (
	'                                                                                                                                ',
	'                                                                                                                                ',
	'                                                                                                                                ',
	'                                                                                                                                ',
	'                                                                                                                                ',
	'                                  X                                                                                             ',
	'                                   XXX                                                                                          ',
	'                                   XXXXX                                                                                        ',
	'                                 X  XXX XX                                                                                      ',
	'                           XXXXXXX XXXXXXXXXX                                                                                   ',
	'                              XXXXXXXXXXXXXXXXX                                                                                 ',
	'                                XXXXXXXXXXXXXXXX                                                                                ',
	'                                   XX XXXXXX XXX                                                                                ',
	'                                     XXXXXXXXXXXX                                                                               ',
	'                                          XXXXXXXX                                                                              ',
	'                                                  XX                                                                            ',
	'                                                    XX                                                                          ',
	'                                                       XX                                                                       ',
	'                                                          X                                                                     ',
	'                                                            XX                                                                  ',
	'                                                               X                                                                ',
	'                                                                 XX                                                             ',
	'                                                                   XX                                                           ',
	'                                                                      XX                                                        ',
	'                                                                        XX                                                      ',
	'                                                                           XX                                                   ',
	'                                                                             XX                                                 ',
	'                                                                                XX                                              ',
	'                                                                                  XX                                            ',
	'                                                                                     XX                                         ',
	'                                                                                       XX                                       ',
	'                                                                                          XX   X                                ',
	'                                                                                            XXXXX                               ',
	'                                                                                          XXXXXXXX                              ',
	'                                                                                           XXXXXXXX                             ',
	'                                                                                          XX XX XX                              ',
	'                                                                                                                                ',
	'                                                                                                                                ',
	'                                                                                                                                ',
	'                                                                                                                                '
	)

NEArrow = (
	'                                                                                                                                ',
	'                                                                                                                                ',
	'                                                                                                                                ',
	'                                                                                                                                ',
	'                                                                                                                                ',
	'                                                                                                                                ',
	'                                                                                                                                ',
	'                                                                                          XXXXXXX                               ',
	'                                                                                            XX XX                               ',
	'                                                                                         XX    X                                ',
	'                                                                                       XX                                       ',
	'                                                                                    XX                                          ',
	'                                                                                  XX                                            ',
	'                                                                               XX                                               ',
	'                                                                             XX                                                 ',
	'                                                                          XX                                                    ',
	'                                                                        XX                                                      ',
	'                                                                     XX                                                         ',
	'                                                                   XX                                                           ',
	'                                                                 X                                                              ',
	'                                                              XX                                                                ',
	'                                                           XX                                                                   ',
	'                                                         XX                                                                     ',
	'                                                      XX                                                                        ',
	'                                                    XX                                                                          ',
	'                                                 XX                                                                             ',
	'                                       XXXXXXXXXXX                                                                              ',
	'                                    XXXXXXX  XXXX                                                                               ',
	'                                  XXXXXXXXXXXXXXX                                                                               ',
	'                               XXXXX XXXXXXX XXX                                                                                ',
	'                             XXXXXXXXXXX XXXXXX                                                                                 ',
	'                          XXXX     X XXXXXXXX                                                                                   ',
	'                            X       XXXXXX                                                                                      ',
	'                                    XXX                                                                                         ',
	'                                   XX                                                                                           ',
	'                                                                                                                                ',
	'                                                                                                                                ',
	'                                                                                                                                ',
	'                                                                                                                                ',
	'                                                                                                                                '
	)

NWArrow = (
	'                                                                                                                                ',
	'                                                                                                                                ',
	'                                                                                                                                ',
	'                                                                                                                                ',
	'                                                                                                                                ',
	'                                                                                                                                ',
	'                               XXX                                                                                              ',
	'                                XXX  X                                                                                          ',
	'                                 X  XX                                                                                          ',
	'                                      XX                                                                                        ',
	'                                         XX                                                                                     ',
	'                                           XX                                                                                   ',
	'                                              XX                                                                                ',
	'                                                XX                                                                              ',
	'                                                   XX                                                                           ',
	'                                                     XX                                                                         ',
	'                                                        XX                                                                      ',
	'                                                          XX                                                                    ',
	'                                                             XX                                                                 ',
	'                                                               XX                                                               ',
	'                                                                  XX                                                            ',
	'                                                                    XX                                                          ',
	'                                                                       XX                                                       ',
	'                                                                         XX                                                     ',
	'                                                                            XX                                                  ',
	'                                                                              XXX                                               ',
	'                                                                               XXXXXXXXXXXX                                     ',
	'                                                                                XXXXXXXXXXXXX                                   ',
	'                                                                                XXXXXXXXXXXXXXXX                                ',
	'                                                                                 XXX XXXXXXXXXX XX                              ',
	'                                                                                   XXXXX XXXXXXXXXXXX                           ',
	'                                                                                      XXXXXXXXX                                 ',
	'                                                                                        XXXXX                                   ',
	'                                                                                          XXXX                                  ',
	'                                                                                             X X                                ',
	'                                                                                                                                ',
	'                                                                                                                                ',
	'                                                                                                                                ',
	'                                                                                                                                ',
	'                                                                                                                                '
	)
